### PR TITLE
Use BadRequest for bad requests in postgres example

### PR DESCRIPTION
**Pull request by globin**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 81238151277908d280825198c4708617c7979dd3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless

---
This message was auto-generated by https://gitcop.com

**Comment by s-panferov** [comment]
@globin thanks for your PR! Nice catch! Could you please update your commit message according to https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md? If you have no time, just say and I do it myself manually.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2fd90c0cde11417736fb1d4d3ff8000bc2211096
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by globin** [comment]
Updated

**Comment by s-panferov** [comment]
Thanks!

**Pull request merged**
