### PR TITLE
refactor(*): rustc 1.0.0-beta.4

### LINKED ISSUE #40: Followup: Does not compile with beta
From this issue: #38 

This should work before the 1.0 release to ensure it will work with 1.0 as well.

### PR DESCRIPTION
**Pull request by flaub**
Fixes #40.

Requires the following PRs to land:
* rustless/queryst#5
* rustless/valico#10
* chris-morgan/mopa#2

### CODE REVIEW

**Comment by s-panferov** [comment]
@flaub it's awesome! I'll look at this PR and at the related PRs tomorrow morning (GMT+3). Sorry for the delay.

**Comment by flaub** [comment]
My pleasure, this is giving me a good introduction to rust!

**Comment by allan-simon** [comment]
what's the status on it ? :)

**Comment by s-panferov** [comment]
@allan-simon the major blocker right now is https://github.com/chris-morgan/mopa/pull/2.

**Pull request merged**
