### PR TITLE
Include correct URLs in metadata

### PR DESCRIPTION
**Pull request by badboy**
Currently it links the repo to crates.io and the homepage to the repository. 
As there is a dedicated homepage and the documentation is hosted as well, just link there.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 31b81b02b55c96a35dba62bf2f8a2c815cf6e8e9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 107aa2f0153be6670cfc8d30dbb22fc6355ae6ec
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by badboy** [comment]
Force-pushed with updated commit message.

**Comment by badboy** [comment]
Oh look, the build broke because #52

**Comment by s-panferov** [comment]
Thanks!

**Pull request merged**
