### PR TITLE
Fix compilation errors with rust 1.7.0

### PR DESCRIPTION
**Pull request by cpick**
Bump hyper and iron versions and make some small changes to build cleanly with
the latest version of rust.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d99e8ce2c3d86d53f435d2955ec46fab3b01e0c8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 546511fd3e3cf3c3cc4966c9df4850c9a529d679
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/rustless/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by s-panferov** [comment]
Thanks! Awesome!

**Comment by s-panferov** [comment]
Landed as v0.7.3

**Pull request merged**
